server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_authuser
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgresSQLDialect
        show_sql: true
        jdbc.lob.non_contextual_creation: true